language: php

php:
  - 5.6
  - 7

env:
  global:
    - MODULE_NAME='config_ignore_keys'
    - MODULE_TEST_GROUP='config_ignore_keys'
    - DRUPAL_VERSION='^8.4.0'

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  # Ensure we have the latest sources.
  - sudo apt-get -y update

  # Composer.
  - sed -i '1i export PATH="$HOME/.composer/vendor/bin:$PATH"' $HOME/.bashrc
  - source $HOME/.bashrc
  - composer self-update

  # Drush.
  - composer global require "youngj/httpserver:dev-master#41dd2b7"
  - composer global require drush/drush:dev-master

  # Coder.
  - composer global require drupal/coder:^8.2.12
  - composer global require dealerdirect/phpcodesniffer-composer-installer
  - phpcs -i

  # Ensure the PHP environment is ready.
  - phpenv rehash

install:
  # Basic PHP packages.
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # Move the checked out module into the correct structure.
  - mkdir /tmp/$MODULE_NAME
  - mv * /tmp/$MODULE_NAME/
  - composer require drupal/drupal:$DRUPAL_VERSION
  - mv ./vendor/drupal/drupal ./drupal
  - mv /tmp/$MODULE_NAME drupal/modules/

before_script:
  # This fixes a fail when install Drupal.
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

  # Install Drupal and enable the required modules (including this one).
  - mysql -e 'create database drupal;'
  - cd $TRAVIS_BUILD_DIR/drupal && composer install
  - cd $TRAVIS_BUILD_DIR/drupal && drush --yes site-install testing --db-url="mysql://root@127.0.0.1/drupal"
  - cd $TRAVIS_BUILD_DIR/drupal && drush --yes en $MODULE_NAME
  - cd $TRAVIS_BUILD_DIR/drupal && drush --yes en simpletest

  # Start a web server.
  - drush runserver 127.0.0.1:8080 &
  - until netstat -an 2>/dev/null | grep '8080.*LISTEN'; do true; done

script:
  - phpcs --report=full --standard=Drupal,DrupalPractice $TRAVIS_BUILD_DIR/drupal/modules/$MODULE_NAME
  - if [ $MODULE_TEST_GROUP ] ; then php $TRAVIS_BUILD_DIR/drupal/core/scripts/run-tests.sh --php `which php` --concurrency 12 --url http://127.0.0.1:8080 --color "$MODULE_TEST_GROUP"; fi
